const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('manager', {
    getData: () => ipcRenderer.invoke('data:get'),
    addSite: (data) => ipcRenderer.invoke('sites:add', data),
    removeSite: (id) => ipcRenderer.invoke('sites:remove', id),
    addAccount: (data) => ipcRenderer.invoke('accounts:add', data),
    removeAccount: (id) => ipcRenderer.invoke('accounts:remove', id),
    switchAccount: (id) => ipcRenderer.invoke('accounts:switch', id),
    renameAccount: (id, name) => ipcRenderer.invoke('accounts:rename', { id, name }),
    updateAccount: (id, name, url, proxy, icon, iconColor) => ipcRenderer.invoke('accounts:update', { id, name, url, proxy, icon, iconColor }),
    renameSite: (id, name) => ipcRenderer.invoke('sites:rename', { id, name }),
    updateSite: (id, name, icon, iconColor) => ipcRenderer.invoke('sites:update', { id, name, icon, iconColor }),
    reorderAccounts: (siteId, orderedIds) => ipcRenderer.invoke('accounts:reorder', { siteId, orderedIds }),
    reorderSites: (orderedSiteIds) => ipcRenderer.invoke('sites:reorder', orderedSiteIds),
    reloadAccount: (id) => ipcRenderer.invoke('accounts:reload', id),
    getStats: () => ipcRenderer.invoke('accounts:stats'),
    hideActiveView: (forget) => ipcRenderer.invoke('ui:hide-active-view', forget),
    showActiveView: () => ipcRenderer.invoke('ui:show-active-view'),
    exportData: () => ipcRenderer.invoke('data:export'),
    importData: () => ipcRenderer.invoke('data:import'),
    toggleFullscreen: () => ipcRenderer.invoke('ui:toggle-fullscreen'),
    toggleAccountManualDisable: (id) => ipcRenderer.invoke('accounts:toggle-manual-disable', id),
    toggleSiteManualDisable: (siteId) => ipcRenderer.invoke('sites:toggle-manual-disable', siteId),
});
